FROM node:22.16.0-alpine3.22 AS migrate
WORKDIR /app

# Copy everything needed for migrations
COPY package.json package-lock.json ./

ENV NODE_ENV=development

RUN npm ci

COPY . .

# Set entrypoint to run migration and exit
# CMD ["node", "ace", "migration:run"]
CMD ["node", "ace", "migration:run"]
